"""Write `tools/viewer/build-stamp.js` — the corpus fingerprint the viewer
appends to every article-JSON fetch as `?v=…`.

WHY THIS EXISTS.  Article JSONs ship `public, max-age=31536000, immutable`
(deploy.sh), justified in a comment as "a hash's bytes never change".  That
premise is false: the stable_id hash is a pure function of the article's SECTION
SLUG, not of its content, so a rebuild rewrites the same key with new bytes.  A
CloudFront invalidation clears the edge but not browsers, so a returning reader
keeps pre-deploy article bytes for up to a year — proven live 2026-07-27 on the
user's own browser, and total on 2026-08-11 when the page-position rebuild
changed all 37,228 articles ([[project_client_perf_queue]] item 3).

Adding `?v={fingerprint}` gives the browser a new URL, so it must fetch; the
bytes it gets are fresh because deploy.sh invalidates the edge in the same run.
This COMPOSES with `immutable` rather than fighting it: within a build the URL is
stable and caches hard, and it changes exactly once per corpus change.

CONTENT, NOT CLOCK.  A timestamp would change on every rebuild even when the
corpus is byte-identical — busting every reader's cache for nothing, and
breaking the A/B-identical property the determinism arc established
([[project_determinism_arc]]).  So the fingerprint is a hash of the article
JSONs themselves: it moves if and only if what we serve moves.

Run from the repo root (rebuild_all.sh Phase 6.2, AFTER post-export has patched
the JSONs)::

    uv run python tools/viewer/build_stamp.py
"""
from __future__ import annotations

import hashlib
import sys
from pathlib import Path

ARTICLES = Path("data/derived/articles")
OUT = Path("tools/viewer/build-stamp.js")


def fingerprint() -> str:
    """12 hex over every article JSON, in name order.

    Name order (not directory order) so the value is independent of the
    filesystem's enumeration; the NAME goes into the hash too, so a rename with
    identical bytes still moves the stamp.
    """
    h = hashlib.sha256()
    n = 0
    for p in sorted(ARTICLES.glob("*.json")):
        h.update(p.name.encode("utf-8"))
        h.update(p.read_bytes())
        n += 1
    if not n:
        raise SystemExit(
            f"no article JSONs under {ARTICLES} — refusing to stamp a build "
            "that has no corpus (a stamp over nothing is a constant, which "
            "would silently stop busting caches forever)")
    return h.hexdigest()[:12], n


def main() -> int:
    fp, n = fingerprint()
    OUT.write_text(
        "// GENERATED by tools/viewer/build_stamp.py — do not edit.\n"
        "// Corpus fingerprint; the viewer appends it to article fetches as\n"
        "// ?v=… so a rebuild's new bytes are not masked by an immutable\n"
        "// browser cache entry.  Served no-cache, so it is always current.\n"
        f'window.BUILD_V = "{fp}";\n',
        encoding="utf-8")
    print(f"build stamp: {fp}  (over {n} article JSONs) -> {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
