"""Wikisource `Module:Table_style/styles` + `/aliases` mirror.

Mechanically converted from
  https://en.wikisource.org/wiki/Module:Table_style/styles
  https://en.wikisource.org/wiki/Module:Table_style/aliases
via `tools/_scratch/lua_to_py.py`.  Source-of-truth lives on wikisource;
refresh this file by re-running the converter and pasting the output.
"""
from __future__ import annotations

# TS_STYLES — 262 entries — from wikisource Module:Table_style
TS_STYLES = {
    'ar': 'text-align:right',
    'ac': 'text-align:center',
    'al': 'text-align:left',
    'aj': 'text-align:justify',
    'all': 'text-align-last:left',
    'alc': 'text-align-last:center',
    'alr': 'text-align-last:right',
    'auxtoc': 'background:#E6F2E6;color:#202122',
    'bgt': 'background-color:transparent;color:inherit',
    'bc': 'border-collapse:collapse',
    'bl': 'border-left:1px solid',
    'br': 'border-right:1px solid',
    'bt': 'border-top:1px solid',
    'bb': 'border-bottom:1px solid',
    'ba': 'border:1px solid',
    'bn': 'border:none',
    'btt': 'border-top:0px solid transparent',
    'bbt': 'border-bottom:0px solid transparent',
    'blt': 'border-left:0px solid transparent',
    'brt': 'border-right:0px solid transparent',
    'btt1': 'border-top:1px solid transparent',
    'bbt1': 'border-bottom:1px solid transparent',
    'blt1': 'border-left:1px solid transparent',
    'brt1': 'border-right:1px solid transparent',
    'ba2': 'border:2px solid',
    'bl2': 'border-left:2px solid',
    'br2': 'border-right:2px solid',
    'bt2': 'border-top:2px solid',
    'bb2': 'border-bottom:2px solid',
    'ba3': 'border:3px solid',
    'bl3': 'border-left:3px solid',
    'br3': 'border-right:3px solid',
    'bt3': 'border-top:3px solid',
    'bb3': 'border-bottom:3px solid',
    'bad': 'border:4px double',
    'bld': 'border-left:4px double',
    'brd': 'border-right:4px double',
    'btd': 'border-top:4px double',
    'bb4xd': 'border-bottom:4px double',
    'ba.': 'border:1px dotted',
    'bl.': 'border-left:1px dotted',
    'br.': 'border-right:1px dotted',
    'br2.': 'border-right:2px dotted',
    'bt.': 'border-top:1px dotted',
    'bb.': 'border-bottom:1px dotted',
    'bb2.': 'border-bottom:2px dotted',
    'db': 'display:block',
    'dc': 'display:contents',
    'df': 'display:flex',
    'di': 'display:inline',
    'dib': 'display:inline-block',
    'dn': 'display:none',
    'dt': 'display:table',
    'h0': 'height:0',
    'h5': 'height:5%',
    'h10': 'height:10%',
    'h15': 'height:15%',
    'h17': 'height:calc(100% / 6)',
    'h20': 'height:20%',
    'h25': 'height:25%',
    'h30': 'height:30%',
    'h33': 'height:calc(100% / 3)',
    'h40': 'height:40%',
    'h50': 'height:50%',
    'h60': 'height:60%',
    'h67': 'height:calc(100% / 1.5)',
    'h70': 'height:70%',
    'h75': 'height:75%',
    'h80': 'height:80%',
    'h83': 'height:calc(100% / 1.2)',
    'h90': 'height:90%',
    'h100': 'height:100%',
    'hmax': 'height:max-content',
    'hmin': 'height:min-content',
    'mc': 'margin:0 auto 0 auto',
    'ma': 'margin-right:auto; margin-left:auto',
    'ma5': 'margin:5px',
    'mt5': 'margin-top:5px',
    'mr5': 'margin-right:5px',
    'mb5': 'margin-bottom:5px',
    'ml5': 'margin-left:5px',
    'ma10': 'margin:10px',
    'mt10': 'margin-top:10px',
    'mr10': 'margin-right:10px',
    'mb10': 'margin-bottom:10px',
    'ml10': 'margin-left:10px',
    'lh90': 'line-height:90%',
    'lh95': 'line-height:95%',
    'lh100': 'line-height:100%',
    'lh110': 'line-height:110%',
    'lh120': 'line-height:120%',
    'lh130': 'line-height:130%',
    'lh150': 'line-height:150%',
    'lh200': 'line-height:200%',
    'lh250': 'line-height:250%',
    'lh300': 'line-height:300%',
    'ffs': 'font-family:serif',
    'ffn': 'font-family:sans-serif',
    'asc': 'font-variant:all-small-caps',
    'sc': 'font-variant:small-caps',
    'fvn': 'font-variant:normal',
    'fs058': 'font-size:58%',
    'fs069': 'font-size:69%',
    'fs083': 'font-size:83%',
    'fs080': 'font-size:80%',
    'fs085': 'font-size:85%',
    'fs090': 'font-size:90%',
    'fs092': 'font-size:92%',
    'fs095': 'font-size:95%',
    'fs105': 'font-size:105%',
    'fs110': 'font-size:110%',
    'fs120': 'font-size:120%',
    'fs130': 'font-size:130%',
    'fs144': 'font-size:144%',
    'fs182': 'font-size:182%',
    'fs207': 'font-size:207%',
    'fs249': 'font-size:249%',
    'fs260': 'font-size:260%',
    'fs280': 'font-size:280%',
    'fs300': 'font-size:300%',
    'uc': 'text-transform:uppercase',
    'lc': 'text-transform:lowercase',
    'cap': 'text-transform:capitalize',
    'fll': 'float:left',
    'flr': 'float:right',
    'fsn': 'font-style:normal',
    'fsi': 'font-style:italic',
    'fwn': 'font-weight:normal',
    'fwb': 'font-weight:bold',
    'fwbfsi': 'font-weight:bold;font-style:italic',
    'ofh': 'overflow:hidden',
    'itp': 'padding-left:2em; text-indent:-1em',
    'itp.5': 'padding-left:2.5em; text-indent:-2em',
    'it1p.5': 'padding-left:1.5em; text-indent:-1em',
    'it1p2': 'padding-left:3em; text-indent:-1em',
    'it': 'padding-left:2em; text-indent:-2em',
    'it1': 'padding-left:1em; text-indent:-1em',
    'it32': 'padding-left:3em; text-indent:-2em',
    'it42': 'padding-left:4em; text-indent:-2em',
    'it52': 'padding-left:5em; text-indent:-2em',
    'p0': 'padding:0',
    'p.5': 'padding:0.5em',
    'p1': 'padding:1em',
    'p1.5': 'padding:1.5em',
    'p2': 'padding:2em',
    'p2.5': 'padding:2.5em',
    'p3': 'padding:3em',
    'p3.5': 'padding:3.5em',
    'p4': 'padding:4em',
    'p5': 'padding:5em',
    'p6': 'padding:6em',
    'p7': 'padding:7em',
    'plr0': 'padding-left:0em; padding-right:0em',
    'plr.5': 'padding-left:0.5em; padding-right:0.5em',
    'plr1': 'padding-left:1em; padding-right:1em',
    'plr1.5': 'padding-left:1.5em; padding-right:1.5em',
    'plr2': 'padding-left:2em; padding-right:2em',
    'plr2.5': 'padding-left:2.5em; padding-right:2.5em',
    'plr3': 'padding-left:3em; padding-right:3em',
    'plr3.5': 'padding-left:3.5em; padding-right:3.5em',
    'plr4': 'padding-left:4em; padding-right:4em',
    'plr5': 'padding-left:5em; padding-right:5em',
    'plr6': 'padding-left:6em; padding-right:6em',
    'plr7': 'padding-left:7em; padding-right:7em',
    'pl0': 'padding-left:0',
    'pl.5': 'padding-left:0.5em',
    'pl1': 'padding-left:1em',
    'pl1.5': 'padding-left:1.5em',
    'pl2': 'padding-left:2em',
    'pl2.5': 'padding-left:2.5em',
    'pl3': 'padding-left:3em',
    'pl3.5': 'padding-left:3.5em',
    'pl4': 'padding-left:4em',
    'pl5': 'padding-left:5em',
    'pl6': 'padding-left:6em',
    'pl7': 'padding-left:7em',
    'pr0': 'padding-right:0',
    'pr.5': 'padding-right:0.5em',
    'pr1': 'padding-right:1em',
    'pr1.5': 'padding-right:1.5em',
    'pr2': 'padding-right:2em',
    'pr2.5': 'padding-right:2.5em',
    'pr3': 'padding-right:3em',
    'pr3.5': 'padding-right:3.5em',
    'pr4': 'padding-right:4em',
    'pr5': 'padding-right:5em',
    'pr6': 'padding-right:6em',
    'pr7': 'padding-right:7em',
    'ptb0': 'padding-top:0em; padding-bottom:0em',
    'ptb.5': 'padding-top:0.5em; padding-bottom:0.5em',
    'ptb1': 'padding-top:1em; padding-bottom:1em',
    'ptb1.5': 'padding-top:1.5em; padding-bottom:1.5em',
    'ptb2': 'padding-top:2em; padding-bottom:2em',
    'ptb2.5': 'padding-top:2.5em; padding-bottom:2.5em',
    'ptb3': 'padding-top:3em; padding-bottom:3em',
    'ptb3.5': 'padding-top:3.5em; padding-bottom:3.5em',
    'ptb4': 'padding-top:4em; padding-bottom:4em',
    'ptb5': 'padding-top:5em; padding-bottom:5em',
    'ptb6': 'padding-top:6em; padding-bottom:6em',
    'ptb7': 'padding-top:7em; padding-bottom:7em',
    'pt0': 'padding-top:0',
    'pt.5': 'padding-top:0.5em',
    'pt1': 'padding-top:1em',
    'pt1.5': 'padding-top:1.5em',
    'pt2': 'padding-top:2em',
    'pt2.5': 'padding-top:2.5em',
    'pt3': 'padding-top:3em',
    'pt3.5': 'padding-top:3.5em',
    'pt4': 'padding-top:4em',
    'pt5': 'padding-top:5em',
    'pt6': 'padding-top:6em',
    'pt7': 'padding-top:7em',
    'pb0': 'padding-bottom:0',
    'pb.5': 'padding-bottom:0.5em',
    'pb1': 'padding-bottom:1em',
    'pb1.5': 'padding-bottom:1.5em',
    'pb2': 'padding-bottom:2em',
    'pb2.5': 'padding-bottom:2.5em',
    'pb3': 'padding-bottom:3em',
    'pb3.5': 'padding-bottom:3.5em',
    'pb4': 'padding-bottom:4em',
    'pb5': 'padding-bottom:5em',
    'pb6': 'padding-bottom:6em',
    'pb7': 'padding-bottom:7em',
    'abs': 'position:absolute',
    'rel': 'position:relative',
    'ltr': 'direction:ltr',
    'rtl': 'direction:rtl',
    'tds': 'text-decoration:line-through',
    'tdu': 'text-decoration:underline',
    'vtt': 'vertical-align:text-top',
    'vtb': 'vertical-align:text-bottom',
    'vtp': 'vertical-align:top',
    'vbs': 'vertical-align:baseline',
    'vbm': 'vertical-align:bottom',
    'vmi': 'vertical-align:middle',
    'w0': 'width:0',
    'w5': 'width:5%',
    'w10': 'width:10%',
    'w15': 'width:15%',
    'w17': 'width:calc(100% / 6)',
    'w20': 'width:20%',
    'w25': 'width:25%',
    'w30': 'width:30%',
    'w33': 'width:calc(100% / 3)',
    'w35': 'width:35%',
    'w40': 'width:40%',
    'w45': 'width:45%',
    'w50': 'width:50%',
    'w60': 'width:60%',
    'w67': 'width:calc(100% / 1.5)',
    'w70': 'width:70%',
    'w75': 'width:75%',
    'w80': 'width:80%',
    'w83': 'width:calc(100% / 1.2)',
    'w90': 'width:90%',
    'w95': 'width:95%',
    'w100': 'width:100%',
    'wmax': 'width:max-content',
    'wmin': 'width:min-content',
    'wnw': 'white-space:nowrap',
    'flatshadow': 'background-color:#F0F0F0; color:var(--color-base-fixed:#202122;)',
}

# TS_ALIASES — 232 entries — from wikisource Module:Table_style
TS_ALIASES = {
    'right': 'ar',
    'align right': 'ar',
    'right align': 'ar',
    'center': 'ac',
    'centre': 'ac',
    'align center': 'ac',
    'center align': 'ac',
    'align centre': 'ac',
    'centre align': 'ac',
    'left': 'al',
    'align left': 'al',
    'left align': 'al',
    'justify': 'aj',
    'align justify': 'aj',
    'justify align': 'aj',
    'transparent': 'bgt',
    'transparency': 'bgt',
    'border collapse': 'bc',
    'collapse': 'bc',
    'border left': 'bl',
    'left border': 'bl',
    'border right': 'br',
    'right border': 'br',
    'border top': 'bt',
    'top border': 'bt',
    'border bottom': 'bb',
    'bottom border': 'bb',
    'border all': 'ba',
    'border': 'ba',
    'border none': 'bn',
    'no border': 'bn',
    'bbd': 'bb4xd',
    'height narrow': 'h0',
    'h1/20': 'h5',
    'h1/10': 'h10',
    'h3/20': 'h15',
    'h1/6': 'h17',
    'h1/5': 'h20',
    'h1/4': 'h25',
    'quarter height': 'h25',
    'h3/10': 'h30',
    'h1/3': 'h33',
    'third height': 'h33',
    'h2/5': 'h40',
    'h1/2': 'h50',
    'half height': 'h50',
    'h3/5': 'h60',
    'h2/3': 'h67',
    'two thirds height': 'h67',
    'h7/10': 'h70',
    'h3/4': 'h75',
    'three quarter height': 'h75',
    'h4/5': 'h80',
    'h5/6': 'h83',
    'h9/10': 'h90',
    'h1': 'h100',
    'ha': 'h100',
    'height all': 'h100',
    'full height': 'h100',
    'brace': 'h100',
    'hf': 'hmax',
    'height max': 'hmax',
    'bracetable': 'hmax',
    'brace table': 'hmax',
    'height min': 'hmin',
    'float': 'mc',
    'float center': 'mc',
    'float centre': 'mc',
    'lh9': 'lh90',
    'lh1': 'lh100',
    'lh10': 'lh100',
    'lh11': 'lh110',
    'lh12': 'lh120',
    'lh13': 'lh130',
    'lh15': 'lh150',
    'lh2': 'lh200',
    'lh20': 'lh200',
    'lh25': 'lh250',
    'lh3': 'lh300',
    'all small caps': 'asc',
    'all small capitals': 'asc',
    'small caps': 'sc',
    'small capitals': 'sc',
    'xx-smaller': 'fs058',
    'xxs': 'fs058',
    'x-smaller': 'fs069',
    'xs': 'fs069',
    'smaller': 'fs083',
    'sm': 'fs083',
    'sm80': 'fs080',
    'sm85': 'fs085',
    'sm90': 'fs090',
    'sm92': 'fs092',
    'fine': 'fs092',
    'sm95': 'fs095',
    'sm110': 'fs110',
    'larger': 'fs120',
    'lg': 'fs120',
    'llg': 'fs130',
    'x-larger': 'fs144',
    'xl': 'fs144',
    'xx-larger': 'fs182',
    '2xl': 'fs182',
    'xxl': 'fs182',
    'xxx-larger': 'fs207',
    '3xl': 'fs207',
    'xxxl': 'fs207',
    'xxxx-larger': 'fs249',
    '4xl': 'fs249',
    'xxxxl': 'fs249',
    'upper case': 'uc',
    'upper-case': 'uc',
    'uppercase': 'uc',
    'lower case': 'lc',
    'lower-case': 'lc',
    'lowercase': 'lc',
    'capitalise': 'cap',
    'capitalize': 'cap',
    'float left': 'fll',
    'float right': 'flr',
    'roman': 'fsn',
    'italic': 'fsi',
    'i': 'fsi',
    'normal': 'fwn',
    'bold': 'fwb',
    'b': 'fwb',
    'fwbsi': 'fwbfsi',
    'bold italic': 'fwbfsi',
    'bi': 'fwbfsi',
    'itp0.5': 'itp.5',
    'itp05': 'itp.5',
    'it1p0.5': 'it1p.5',
    'it1p05': 'it1p.5',
    'hi': 'it',
    'p0.5': 'p.5',
    'p05': 'p.5',
    'p15': 'p1.5',
    'p25': 'p2.5',
    'p35': 'p3.5',
    'plr0.5': 'plr.5',
    'plr05': 'plr.5',
    'plr15': 'plr1.5',
    'plr25': 'plr2.5',
    'plr35': 'plr3.5',
    'pl0.5': 'pl.5',
    'pl05': 'pl.5',
    'pl15': 'pl1.5',
    'pl25': 'pl2.5',
    'pl35': 'pl3.5',
    'pr0.5': 'pr.5',
    'pr05': 'pr.5',
    'pr15': 'pr1.5',
    'pr25': 'pr2.5',
    'pr35': 'pr3.5',
    'ptb0.5': 'ptb.5',
    'ptb05': 'ptb.5',
    'ptb15': 'ptb1.5',
    'ptb25': 'ptb2.5',
    'ptb35': 'ptb3.5',
    'pt0.5': 'pt.5',
    'pt05': 'pt.5',
    'pt15': 'pt1.5',
    'pt25': 'pt2.5',
    'pt35': 'pt3.5',
    'pb0.5': 'pb.5',
    'pb05': 'pb.5',
    'pb15': 'pb1.5',
    'pb25': 'pb2.5',
    'pb35': 'pb3.5',
    'absolute': 'abs',
    'relative': 'rel',
    'strike': 'tds',
    'underline': 'tdu',
    'vertical align text top': 'vtt',
    'text top': 'vtt',
    'vertical align text bottom': 'vtb',
    'text bottom': 'vtb',
    'vertical align top': 'vtp',
    'top': 'vtp',
    'vertical align baseline': 'vbs',
    'baseline': 'vbs',
    'vertical align bottom': 'vbm',
    'bottom': 'vbm',
    'vertical align middle': 'vmi',
    'middle': 'vmi',
    'width narrow': 'w0',
    'narrow': 'w0',
    'w1/20': 'w5',
    'w1/10': 'w10',
    'w3/20': 'w15',
    'w1/6': 'w17',
    'w1/5': 'w20',
    'w1/4': 'w25',
    'quarter width': 'w25',
    'quarter': 'w25',
    'w3/10': 'w30',
    'w1/3': 'w33',
    'third width': 'w33',
    'third': 'w33',
    'w7/20': 'w35',
    'w2/5': 'w40',
    'w9/20': 'w45',
    'w1/2': 'w50',
    'half width': 'w50',
    'half': 'w50',
    'w3/5': 'w60',
    'w2/3': 'w67',
    'two thirds width': 'w67',
    'two thirds': 'w67',
    'two-thirds': 'w67',
    'two third': 'w67',
    'two-third': 'w67',
    'w7/10': 'w70',
    'w3/4': 'w75',
    'three quarter width': 'w75',
    'three quarter': 'w75',
    'three-quarter': 'w75',
    'three quarters': 'w75',
    'three-quarters': 'w75',
    'w4/5': 'w80',
    'w5/6': 'w83',
    'w9/10': 'w90',
    'w19/20': 'w95',
    'w1': 'w100',
    'wa': 'w100',
    'width all': 'w100',
    'full width': 'w100',
    'full': 'w100',
    'wf': 'wmax',
    'width max': 'wmax',
    'width min': 'wmin',
    'nowrap': 'wnw',
}

