"""Resolve previously-unresolved cross-references using LLMs.

For each xref with ``status='unresolved'`` (target text didn't match
any article title via exact / alias / fuzzy lookup), feed the
surrounding context + a candidate list (generated by
``unresolved_xref_candidates.py``) to Claude.  The LLM picks the
right article from the candidates, or returns ``null`` for genuine
misses.

Two-tier strategy:

* **Haiku pass** — cheap, handles the easy-and-medium cases (typo
  fixes, clear single-best-match, modest ambiguity).
* **Sonnet retry** — runs on Haiku-null results with broader context.
  Handles long-tail cases where the right answer requires more
  reasoning.

Single shared cache file (``data/derived/xref_disambiguation_cache.json``)
with the surname-disambig flow.  Each entry records which tier
produced the answer; the resolver applies any cached entry whose
``chosen`` is set.

Cache key: ``{source_stable_id}::{surface_text}::{normalized_target}``.

Usage:
  uv run python tools/xrefs/resolve_unresolved.py --tier haiku --limit 5 --sync
  uv run python tools/xrefs/resolve_unresolved.py --tier haiku
  uv run python tools/xrefs/resolve_unresolved.py --tier sonnet
  uv run python tools/xrefs/resolve_unresolved.py --dry-run
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
import time
from pathlib import Path

import anthropic
from anthropic.types.message_create_params import MessageCreateParamsNonStreaming
from anthropic.types.messages.batch_create_params import Request

sys.stdout.reconfigure(encoding="utf-8")

from britannica.db.models import Article, CrossReference  # noqa: E402
from britannica.db.session import SessionLocal  # noqa: E402
from britannica.export.article_json import stable_id  # noqa: E402


CACHE_FILE = Path("data/derived/xref_disambiguation_cache.json")
CANDIDATES_FILE = Path("unresolved_candidates.json")

MODEL_HAIKU = "claude-haiku-4-5"
MODEL_SONNET = "claude-sonnet-4-6"

CONTEXT_CHARS_BEFORE = 600
CONTEXT_CHARS_AFTER = 600


_PROMPT_COMMON = """You match unresolved cross-references in the
Encyclopaedia Britannica (1911) to the right article from a
candidate list.

The reference's literal text didn't exactly match any article title,
so we generated candidates by fuzzy / word-overlap match.

You will receive:
- A short excerpt from the source article around the reference
- The reference's surface text (the literal phrase containing it)
- The normalized target the source seems to be naming
- A ranked list of candidate articles with stable_id, title, and
  a short excerpt

Return JSON: {"stable_id": "<stable_id>"} chosen verbatim from the
candidate list, or {"stable_id": null}."""

# Two-tier strategy:
#
# Haiku (cheap, fast) is the FILTER.  It commits to a target only
# when the candidate match is obvious — typo fixes, title-form
# mismatches with a strong word overlap, exact-substring matches.
# When the choice requires judgment (does "Jewish Encyclopedia"
# really mean the EB article ENCYCLOPAEDIA?  is "Paradise Lost"
# routed to MILTON?), Haiku returns null and lets the next tier
# decide.  This avoids confident-but-wrong picks on marginal cases
# that the cheap model isn't smart enough to evaluate properly.
SYSTEM_PROMPT_HAIKU = _PROMPT_COMMON + """

**Calibration for this tier: be conservative.  Return null whenever
the right pick requires judgment.**  Examples:

- Typo / orthography / archaic spelling with a clear high-overlap
  match → pick it.  ``'Amora`` → 'AMORA, ``Eusebibus`` → EUSEBIUS.
- Title-form mismatch where one candidate is a near-exact substring
  of the target → pick it.  ``Life of Sir Walter Scott`` →
  SCOTT, SIR WALTER (the article title appears verbatim in the
  reference).
- Anything else — a book whose author should be guessed, a
  generic-topic that might or might not match the broad article,
  candidates that all look weak — return null.  A more capable
  model will retry these later.

The cost of a Haiku-null is one Sonnet retry; the cost of a
Haiku-wrong is a permanent mis-link until someone notices."""

SYSTEM_PROMPT_SONNET = _PROMPT_COMMON + """

**Calibration for this tier: prefer picking over abstaining.**
You're the second pass — Haiku already declined these cases as
requiring judgment.  Apply that judgment.

- Wrong-but-related links are NOT catastrophic in this project.
  The ground state is no link at all; a related-article side-trip
  is usually still useful for the reader.
- Return null ONLY when none of the candidates is even plausibly
  the referent.
- Books and works typically point to the article about the AUTHOR
  or SUBJECT.  ``Paradise Lost`` → MILTON.  ``Wealth of Nations``
  → SMITH, ADAM.  ``Life of Christ`` → JESUS CHRIST.
- Generic-topic references point to the broadest matching article.
  ``Latin Christianity`` → CHRISTIANITY.  ``King James Version`` →
  BIBLE or BIBLE, ENGLISH.
- If no candidate fits and the reference is itself nonsense (a
  template parameter like ``nosc=1``, garbled OCR, etc.), return
  null."""


def _clean_excerpt(text: str, max_chars: int) -> str:
    text = re.sub(r"\x01PAGE:\d+\x01", "", text)
    text = re.sub(r"«LN:[^|]*\|([^«]*)«/LN»", r"\1", text)
    text = re.sub(r"«[^»]*»", "", text)
    text = re.sub(r"\{\{IMG:[^}]*\}\}", "", text)
    text = re.sub(r"\{\{LEGEND:[\s\S]*?\}LEGEND\}", "", text)
    text = re.sub(r"\{\{TABLE[A-Z]?:[\s\S]*?\}TABLE\}", "", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text[:max_chars]


def _context_around(body: str, surface_text: str) -> str:
    idx = body.find(surface_text)
    if idx < 0:
        return _clean_excerpt(body, CONTEXT_CHARS_BEFORE + CONTEXT_CHARS_AFTER)
    start = max(0, idx - CONTEXT_CHARS_BEFORE)
    end = min(len(body), idx + len(surface_text) + CONTEXT_CHARS_AFTER)
    return _clean_excerpt(
        body[start:end],
        CONTEXT_CHARS_BEFORE + CONTEXT_CHARS_AFTER + len(surface_text),
    )


def _cache_key(source_stable_id: str, surface_text: str,
               normalized_target: str) -> str:
    return f"{source_stable_id}::{surface_text}::{normalized_target}"


def build_request(idx: int, model: str, source_excerpt: str,
                  surface_text: str, normalized_target: str,
                  candidates: list[dict]) -> Request:
    candidate_lines = []
    for c in candidates:
        candidate_lines.append(
            f"- stable_id: {c['stable_id']}\n"
            f"  title: {c['title']}\n"
            f"  excerpt: {c.get('excerpt', '')}"
        )
    user_msg = (
        f"Source article excerpt (around the reference):\n{source_excerpt}\n\n"
        f"Reference surface text: {surface_text!r}\n"
        f"Normalized target: {normalized_target!r}\n\n"
        f"Candidate articles:\n" + "\n".join(candidate_lines)
    )
    system_prompt = (
        SYSTEM_PROMPT_HAIKU if model == MODEL_HAIKU else SYSTEM_PROMPT_SONNET
    )
    return Request(
        custom_id=f"un-{idx}",
        params=MessageCreateParamsNonStreaming(
            model=model,
            max_tokens=120,
            system=[{
                "type": "text",
                "text": system_prompt,
                "cache_control": {"type": "ephemeral"},
            }],
            output_config={
                "format": {
                    "type": "json_schema",
                    "schema": {
                        "type": "object",
                        "properties": {
                            "stable_id": {"type": ["string", "null"]},
                        },
                        "required": ["stable_id"],
                        "additionalProperties": False,
                    }
                }
            },
            messages=[{"role": "user", "content": user_msg}],
        ),
    )


def load_cache() -> dict:
    if CACHE_FILE.exists():
        return json.loads(CACHE_FILE.read_text(encoding="utf-8"))
    return {}


def save_cache(cache: dict) -> None:
    CACHE_FILE.parent.mkdir(parents=True, exist_ok=True)
    CACHE_FILE.write_text(
        json.dumps(cache, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--tier", choices=["haiku", "sonnet"], default="haiku")
    ap.add_argument("--limit", type=int, default=0)
    ap.add_argument("--sync", action="store_true",
                    help="use synchronous Messages API (instant; no batch "
                         "discount).  Recommended for small --limit runs.")
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--skip-structured", action="store_true",
                    help="skip Bible references and section-path targets "
                         "(BIBLE/BOOK#chapter:verse, A/B, A: B forms) — "
                         "these have deterministic resolutions that "
                         "shouldn't burn LLM tokens.  Run separately via "
                         "rule-based resolver once that lands.")
    args = ap.parse_args()

    # Patterns matching the deterministic shapes that don't need LLM.
    structured_patterns = [
        re.compile(r"^BIBLE.*[/#:]"),         # Bible refs
        re.compile(r"^[A-Z][A-Z\s]+/[A-Z]"),  # Section path 'A/B'
        re.compile(r"^[A-Z][A-Z\s]+:\s+[A-Z]"),  # 'A: B' (already handled)
    ]

    if not CANDIDATES_FILE.exists():
        print(f"ERROR: {CANDIDATES_FILE} not found.  Run "
              f"tools/diagnostics/unresolved_xref_candidates.py first.",
              file=sys.stderr)
        return 2

    print(f"Tier: {args.tier}")
    cache = load_cache()
    candidate_records = json.loads(
        CANDIDATES_FILE.read_text(encoding="utf-8")
    )
    print(f"Cache entries: {len(cache)}")
    print(f"Candidate records loaded: {len(candidate_records)}")

    # Filter: skip records with no candidates (LLM can't help).
    has_candidates = [r for r in candidate_records if r["candidates"]]
    print(f"Records with ≥1 candidate: {len(has_candidates)}")

    if args.skip_structured:
        before = len(has_candidates)
        has_candidates = [
            r for r in has_candidates
            if not any(p.search(r["normalized_target"])
                       for p in structured_patterns)
        ]
        print(f"After --skip-structured: {len(has_candidates)} "
              f"(skipped {before - len(has_candidates)})")

    # Pull body excerpts for source articles.
    s = SessionLocal()
    source_ids = {r["xref_id"] for r in has_candidates}
    xref_to_source_body: dict[int, str] = {}
    try:
        # We need source body to build context windows.
        xrefs = (
            s.query(CrossReference)
            .filter(CrossReference.id.in_(source_ids))
            .all()
        )
        sources_needed = {x.article_id for x in xrefs}
        bodies = {
            a.id: a.body or ""
            for a in s.query(Article)
            .filter(Article.id.in_(sources_needed))
            .all()
        }
        for x in xrefs:
            xref_to_source_body[x.id] = bodies.get(x.article_id, "")
    finally:
        s.close()

    def _cands_hash(record: dict) -> str:
        """Stable hash of the candidate set for cache invalidation.

        When the candidate generator changes shape (new scoring,
        different cutoffs), the candidate set for a given xref
        changes — and a cached LLM decision against the old set is
        no longer trustworthy.  Comparing hashes lets us re-decide
        on changed candidates while preserving cached decisions
        whose candidates haven't moved.
        """
        ids = sorted(c["stable_id"] for c in record["candidates"])
        return ",".join(ids)

    def _prompt_hash(model: str) -> str:
        """Hash of (model, system prompt).  Cached entries decided
        with a different prompt are stale and should be re-run."""
        prompt = (
            SYSTEM_PROMPT_HAIKU if model == MODEL_HAIKU
            else SYSTEM_PROMPT_SONNET
        )
        return hashlib.sha256(
            f"{model}::{prompt}".encode("utf-8")
        ).hexdigest()[:12]

    cur_prompt_hash = _prompt_hash(
        MODEL_HAIKU if args.tier == "haiku" else MODEL_SONNET
    )

    # Decide which records this tier should attempt.
    to_resolve: list[tuple[dict, str]] = []
    haiku_null_count = 0
    stale_count = 0
    for r in has_candidates:
        key = _cache_key(
            r["source_stable_id"], r["surface_text"],
            r["normalized_target"],
        )
        entry = cache.get(key)
        cur_hash = _cands_hash(r)
        cached_hash = (
            ",".join(sorted(entry.get("candidates", [])))
            if entry else ""
        )
        candidates_changed = bool(entry) and cached_hash != cur_hash
        prompt_changed = bool(entry) and (
            entry.get("prompt_hash") != cur_prompt_hash
        )
        stale = candidates_changed or prompt_changed

        if args.tier == "haiku":
            # Haiku tier: attempt records with no cached result OR
            # records whose candidate set / prompt has changed since
            # the cached attempt.
            if entry and entry.get("chosen") is not None and not stale:
                continue
            if entry and entry.get("tier") == "haiku" and not stale:
                # Already attempted by Haiku with current prompt and
                # candidates — leave null result for Sonnet retry.
                continue
            if stale:
                stale_count += 1
            to_resolve.append((r, key))
        else:  # sonnet
            # Sonnet tier: attempt records where Haiku returned null
            # OR records whose candidates / prompt changed.
            if not entry:
                continue
            if entry.get("chosen") is not None and not stale:
                continue
            if entry.get("tier") != "haiku" and not stale:
                continue
            haiku_null_count += 1
            to_resolve.append((r, key))

    if stale_count:
        print(f"Stale cache entries (candidates changed): {stale_count}")

    if args.tier == "sonnet":
        print(f"Haiku-null entries available for Sonnet retry: "
              f"{haiku_null_count}")

    if args.limit and len(to_resolve) > args.limit:
        print(f"--limit {args.limit}: capping {len(to_resolve)}")
        to_resolve = to_resolve[:args.limit]

    print(f"To resolve this run: {len(to_resolve)}")

    if args.dry_run:
        print("[dry-run]")
        return 0
    if not to_resolve:
        print("Nothing to do.")
        return 0

    model = MODEL_HAIKU if args.tier == "haiku" else MODEL_SONNET
    client = anthropic.Anthropic()

    if args.sync:
        print(f"Calling {model} synchronously...")
        for i, (record, key) in enumerate(to_resolve):
            body = xref_to_source_body.get(record["xref_id"], "")
            ctx = _context_around(body, record["surface_text"])
            req = build_request(
                i, model, ctx, record["surface_text"],
                record["normalized_target"], record["candidates"],
            )
            params = req["params"]
            msg = client.messages.create(**params)
            text = next(
                (b.text for b in msg.content if b.type == "text"), "{}"
            )
            chosen = None
            try:
                parsed = json.loads(text)
                chosen = parsed.get("stable_id")
                valid = {c["stable_id"] for c in record["candidates"]}
                if chosen not in valid:
                    chosen = None
            except Exception:
                chosen = None
            cache[key] = {
                "chosen": chosen,
                "candidates": [c["stable_id"] for c in record["candidates"]],
                "model": model,
                "tier": args.tier,
                "prompt_hash": cur_prompt_hash,
            }
            print(f"  [{i+1}/{len(to_resolve)}] {key}")
            print(f"      → {chosen!r}")
        save_cache(cache)
        print(f"Cache written: {CACHE_FILE}")
        return 0

    # Batch path.
    print(f"Building {len(to_resolve)} batch requests...")
    requests = []
    for i, (record, _key) in enumerate(to_resolve):
        body = xref_to_source_body.get(record["xref_id"], "")
        ctx = _context_around(body, record["surface_text"])
        requests.append(build_request(
            i, model, ctx, record["surface_text"],
            record["normalized_target"], record["candidates"],
        ))

    print("Submitting batch...")
    batch = client.messages.batches.create(requests=requests)
    print(f"Batch ID: {batch.id}")

    while True:
        batch = client.messages.batches.retrieve(batch.id)
        if batch.processing_status == "ended":
            break
        rc = batch.request_counts
        print(f"  {batch.processing_status} "
              f"(processing={rc.processing}, succeeded={rc.succeeded}, "
              f"errored={rc.errored})")
        time.sleep(30)

    print(f"Batch complete. Succeeded: {batch.request_counts.succeeded}")

    for result in client.messages.batches.results(batch.id):
        idx = int(result.custom_id.split("-")[1])
        record, key = to_resolve[idx]
        chosen = None
        if result.result.type == "succeeded":
            text = next(
                (b.text for b in result.result.message.content
                 if b.type == "text"),
                "{}",
            )
            try:
                parsed = json.loads(text)
                chosen = parsed.get("stable_id")
                valid = {c["stable_id"] for c in record["candidates"]}
                if chosen not in valid:
                    chosen = None
            except Exception:
                chosen = None
        cache[key] = {
            "chosen": chosen,
            "candidates": [c["stable_id"] for c in record["candidates"]],
            "model": model,
            "tier": args.tier,
            "prompt_hash": cur_prompt_hash,
        }

    save_cache(cache)
    print(f"Cache written: {CACHE_FILE}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
